#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x1599edf4, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x97defd52, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x609f1c7e, __VMLINUX_SYMBOL_STR(synchronize_net) },
	{ 0xb791bb52, __VMLINUX_SYMBOL_STR(release_sock) },
	{ 0x48fa2796, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xa9ff2135, __VMLINUX_SYMBOL_STR(ethtool_op_get_ts_info) },
	{ 0x443f18af, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0xcccebf94, __VMLINUX_SYMBOL_STR(iov_iter_npages) },
	{ 0x161bd4b5, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x5c2e3421, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x39461d6a, __VMLINUX_SYMBOL_STR(in_egroup_p) },
	{ 0x4d3f749f, __VMLINUX_SYMBOL_STR(generic_xdp_tx) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0x17182455, __VMLINUX_SYMBOL_STR(__skb_flow_dissect) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xc400d64c, __VMLINUX_SYMBOL_STR(skb_copy_datagram_from_iter) },
	{ 0x81742e39, __VMLINUX_SYMBOL_STR(remove_wait_queue) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0xeb95de37, __VMLINUX_SYMBOL_STR(no_llseek) },
	{ 0xe6f2865e, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0x7113e034, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x2930b436, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x3c13c318, __VMLINUX_SYMBOL_STR(sock_alloc_send_pskb) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x9d94f0f8, __VMLINUX_SYMBOL_STR(skb_page_frag_refill) },
	{ 0x848bdf61, __VMLINUX_SYMBOL_STR(sk_detach_filter) },
	{ 0x4547ff90, __VMLINUX_SYMBOL_STR(skb_tx_error) },
	{ 0xd4c82d44, __VMLINUX_SYMBOL_STR(skb_partial_csum_set) },
	{ 0x559b27f8, __VMLINUX_SYMBOL_STR(xdp_do_flush_map) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x8a336222, __VMLINUX_SYMBOL_STR(copy_page_from_iter) },
	{ 0xda02d67, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0x57771e17, __VMLINUX_SYMBOL_STR(skb_copy_ubufs) },
	{ 0xddece99e, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xaad8c7d6, __VMLINUX_SYMBOL_STR(default_wake_function) },
	{ 0x451ff832, __VMLINUX_SYMBOL_STR(__f_setown) },
	{ 0xe8d6301b, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x1e4737c, __VMLINUX_SYMBOL_STR(skb_queue_purge) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x17570799, __VMLINUX_SYMBOL_STR(dev_set_mac_address) },
	{ 0x9a8209cd, __VMLINUX_SYMBOL_STR(dev_get_valid_name) },
	{ 0x755e33b3, __VMLINUX_SYMBOL_STR(netif_tx_wake_queue) },
	{ 0x29816bdd, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{ 0x4eff8c5b, __VMLINUX_SYMBOL_STR(netif_tx_stop_all_queues) },
	{ 0xc5990f22, __VMLINUX_SYMBOL_STR(flow_keys_dissector) },
	{ 0x630efb1a, __VMLINUX_SYMBOL_STR(skb_copy_datagram_iter) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x5669a39d, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0x19ac1202, __VMLINUX_SYMBOL_STR(lock_sock_nested) },
	{ 0xdab1f35c, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xadfc79cb, __VMLINUX_SYMBOL_STR(sock_recv_errqueue) },
	{ 0xf23cb0ab, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x585d2314, __VMLINUX_SYMBOL_STR(fasync_helper) },
	{ 0x8f47237d, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x6220b4a2, __VMLINUX_SYMBOL_STR(crc32_le) },
	{ 0xccde6984, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x266b5ece, __VMLINUX_SYMBOL_STR(netif_set_real_num_rx_queues) },
	{ 0x217ff7a7, __VMLINUX_SYMBOL_STR(sk_attach_filter) },
	{ 0xa38caae0, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xe1f69867, __VMLINUX_SYMBOL_STR(netif_set_real_num_tx_queues) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xe2cdf177, __VMLINUX_SYMBOL_STR(rtnl_link_unregister) },
	{ 0x4c759827, __VMLINUX_SYMBOL_STR(byte_rev_table) },
	{ 0x4e880848, __VMLINUX_SYMBOL_STR(sk_filter_trim_cap) },
	{ 0x760203d3, __VMLINUX_SYMBOL_STR(build_skb) },
	{ 0x6c209eab, __VMLINUX_SYMBOL_STR(__alloc_percpu_gfp) },
	{ 0x88288e85, __VMLINUX_SYMBOL_STR(kvmalloc_node) },
	{ 0x4059792f, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x5bf493d, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xa1a17df4, __VMLINUX_SYMBOL_STR(__wake_up_sync_key) },
	{ 0x945ef781, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x29ba11e, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xe1e3311e, __VMLINUX_SYMBOL_STR(_copy_from_iter_full) },
	{ 0xeefc768a, __VMLINUX_SYMBOL_STR(passthru_features_check) },
	{ 0xaca65ae7, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x9c7d517b, __VMLINUX_SYMBOL_STR(eth_type_trans) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0x577bf0c1, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0x4fc8e0de, __VMLINUX_SYMBOL_STR(__dev_get_by_name) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0x8ec5346c, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0x3232d60, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xaeb35694, __VMLINUX_SYMBOL_STR(eth_validate_addr) },
	{ 0x41864fc, __VMLINUX_SYMBOL_STR(xdp_do_redirect) },
	{ 0x3fb2b1cc, __VMLINUX_SYMBOL_STR(add_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x70c75c41, __VMLINUX_SYMBOL_STR(rtnl_link_register) },
	{ 0xfd032d4e, __VMLINUX_SYMBOL_STR(kill_fasync) },
	{ 0x4f4bbfbb, __VMLINUX_SYMBOL_STR(iov_iter_advance) },
	{ 0x4f43739e, __VMLINUX_SYMBOL_STR(bpf_warn_invalid_xdp_action) },
	{ 0xc53507a8, __VMLINUX_SYMBOL_STR(do_xdp_generic) },
	{ 0xe2e8065e, __VMLINUX_SYMBOL_STR(memdup_user) },
	{ 0x91578019, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x9719d81a, __VMLINUX_SYMBOL_STR(netdev_update_features) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x5c41ff32, __VMLINUX_SYMBOL_STR(skb_tstamp_tx) },
	{ 0x590ba4fa, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0xfcb954b5, __VMLINUX_SYMBOL_STR(eth_mac_addr) },
	{ 0xf0f388d5, __VMLINUX_SYMBOL_STR(zerocopy_sg_from_iter) },
	{ 0xbfb9aea8, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0x1adb2f16, __VMLINUX_SYMBOL_STR(_copy_to_iter) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0xfd20e32c, __VMLINUX_SYMBOL_STR(__put_page) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x8d56cd57, __VMLINUX_SYMBOL_STR(__skb_get_hash_symmetric) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

