#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="4.14.71-ev3dev-2.3.0-ev3+" --arg="/boot/vmlinuz-4.14.71-ev3dev-2.3.0-ev3+" /etc/kernel/postinst.d
exit 0
