#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x1599edf4, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe9c43a24, __VMLINUX_SYMBOL_STR(proc_dointvec_minmax) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xe79f3cac, __VMLINUX_SYMBOL_STR(locks_copy_lock) },
	{ 0x48fa2796, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xe0a1361b, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x528c709d, __VMLINUX_SYMBOL_STR(simple_read_from_buffer) },
	{ 0x28f38dc7, __VMLINUX_SYMBOL_STR(register_sysctl_table) },
	{ 0x46034416, __VMLINUX_SYMBOL_STR(param_get_int) },
	{ 0xca9745ae, __VMLINUX_SYMBOL_STR(locks_start_grace) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xf68285c0, __VMLINUX_SYMBOL_STR(register_inetaddr_notifier) },
	{ 0xad73041f, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xf50b2d0b, __VMLINUX_SYMBOL_STR(svc_print_addr) },
	{ 0xc22d8fbd, __VMLINUX_SYMBOL_STR(svc_sock_update_bufs) },
	{ 0x5abbfd95, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0xc3880471, __VMLINUX_SYMBOL_STR(xdr_decode_netobj) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1d4ba735, __VMLINUX_SYMBOL_STR(svc_find_xprt) },
	{ 0x7adeb8d4, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0xbe038bb3, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x60352082, __VMLINUX_SYMBOL_STR(register_inet6addr_notifier) },
	{ 0xed02c13, __VMLINUX_SYMBOL_STR(rpc_restart_call) },
	{ 0xf2204811, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xfd792e2a, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x5fc262cb, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x9c01f471, __VMLINUX_SYMBOL_STR(rpc_force_rebind) },
	{ 0x3c77a4e7, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0xda02d67, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xe89af961, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0x2021eaf2, __VMLINUX_SYMBOL_STR(svc_set_client) },
	{ 0x5dc627a6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xffa8302, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0xddece99e, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2fe252cc, __VMLINUX_SYMBOL_STR(unregister_inet6addr_notifier) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x9409dc7f, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x284736af, __VMLINUX_SYMBOL_STR(vfs_lock_file) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xf0f2aa6f, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x6dce6a15, __VMLINUX_SYMBOL_STR(proc_mkdir) },
	{ 0x82b6cd0a, __VMLINUX_SYMBOL_STR(rpc_call_sync) },
	{ 0x7ab628c1, __VMLINUX_SYMBOL_STR(default_llseek) },
	{ 0xfd2cb988, __VMLINUX_SYMBOL_STR(svc_create) },
	{ 0x4dacf3d9, __VMLINUX_SYMBOL_STR(rpc_call_start) },
	{ 0xfda0d6e6, __VMLINUX_SYMBOL_STR(svc_destroy) },
	{ 0xe4cc55ee, __VMLINUX_SYMBOL_STR(rpc_create) },
	{ 0x201a4b32, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x42774dfc, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xb82db842, __VMLINUX_SYMBOL_STR(proc_doulongvec_minmax) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xb097c25e, __VMLINUX_SYMBOL_STR(vfs_cancel_lock) },
	{ 0x195a71c2, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xa9f0327a, __VMLINUX_SYMBOL_STR(svc_process) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0xabf408c4, __VMLINUX_SYMBOL_STR(svc_rpcb_cleanup) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xe7372bf2, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xd3512349, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x525a83d2, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xb22e32a7, __VMLINUX_SYMBOL_STR(svc_age_temp_xprts_now) },
	{ 0xfe487975, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x18976784, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0x1afa901d, __VMLINUX_SYMBOL_STR(svc_xprt_put) },
	{ 0x8657a8ed, __VMLINUX_SYMBOL_STR(simple_transaction_release) },
	{ 0xb340148f, __VMLINUX_SYMBOL_STR(__rpc_wait_for_completion_task) },
	{ 0x7c1641b9, __VMLINUX_SYMBOL_STR(svc_create_xprt) },
	{ 0x945ef781, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x5c71519e, __VMLINUX_SYMBOL_STR(locks_init_lock) },
	{ 0xfe029963, __VMLINUX_SYMBOL_STR(unregister_inetaddr_notifier) },
	{ 0xe9ae78b6, __VMLINUX_SYMBOL_STR(locks_release_private) },
	{ 0x5786834, __VMLINUX_SYMBOL_STR(unregister_sysctl_table) },
	{ 0x58d2273e, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x2eec63c9, __VMLINUX_SYMBOL_STR(xdr_encode_netobj) },
	{ 0x8ddd8aad, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x65fd066a, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xa9a681c2, __VMLINUX_SYMBOL_STR(locks_lock_inode_wait) },
	{ 0x511b6a49, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x9b27bdb5, __VMLINUX_SYMBOL_STR(locks_in_grace) },
	{ 0x9b8832a0, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x42f3c53b, __VMLINUX_SYMBOL_STR(rpc_run_task) },
	{ 0xde97c8ac, __VMLINUX_SYMBOL_STR(param_get_ulong) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0x413c0466, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xea7b6023, __VMLINUX_SYMBOL_STR(svc_shutdown_net) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x93f6bff1, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x2f8ebbe0, __VMLINUX_SYMBOL_STR(rpc_ntop) },
	{ 0xa8224682, __VMLINUX_SYMBOL_STR(posix_unblock_lock) },
	{ 0x9ef02479, __VMLINUX_SYMBOL_STR(svc_exit_thread) },
	{ 0x54496b4, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0x1aeab862, __VMLINUX_SYMBOL_STR(vfs_test_lock) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x67dfead8, __VMLINUX_SYMBOL_STR(simple_transaction_get) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6df1aaf1, __VMLINUX_SYMBOL_STR(kernel_sigaction) },
	{ 0xfc36d0d4, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x6128b5fc, __VMLINUX_SYMBOL_STR(__printk_ratelimit) },
	{ 0xf1ea6f1c, __VMLINUX_SYMBOL_STR(__bswapsi2) },
	{ 0x6f284de8, __VMLINUX_SYMBOL_STR(svc_xprt_do_enqueue) },
	{ 0x386f0158, __VMLINUX_SYMBOL_STR(refcount_dec_and_mutex_lock) },
	{ 0x166f41e, __VMLINUX_SYMBOL_STR(svc_prepare_thread) },
	{ 0x963e0acd, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1fe1e1ad, __VMLINUX_SYMBOL_STR(locks_end_grace) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0xd3dbcc72, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xc9970769, __VMLINUX_SYMBOL_STR(svc_recv) },
	{ 0x9ff04e88, __VMLINUX_SYMBOL_STR(proc_create) },
	{ 0x8fda254c, __VMLINUX_SYMBOL_STR(svc_bind) },
	{ 0xc78c8eca, __VMLINUX_SYMBOL_STR(rpc_shutdown_client) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x8652ae31, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x2919b156, __VMLINUX_SYMBOL_STR(xdr_decode_string_inplace) },
	{ 0x4063803a, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x3280383e, __VMLINUX_SYMBOL_STR(svc_wake_up) },
	{ 0xfb12626f, __VMLINUX_SYMBOL_STR(rpc_put_task) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=grace,sunrpc";

